const modes = {
  cognitive: {
    title: 'Cognitive mode',
    features: [
      ['access', 'Mental access finder'],
      ['routine', 'Daily routine reminders'],
      ['meds', 'Medication tracker'],
      ['games', 'Cognitive skills games'],
      ['mood', 'Mood check-in'],
    ],
  },
  motor: {
    title: 'Motor mode',
    features: [
      ['body', 'Body check-in'],
      ['physical', 'Physical access finder'],
      ['large', 'Large touch layout'],
      ['voice', 'Persistent voice control'],
    ],
  },
  speech: {
    title: 'Speech mode',
    features: [
      ['speechPlaces', 'Speech-friendly places'],
      ['board', 'Conversation board'],
      ['lessons', 'Guided speech lessons'],
    ],
  },
};

const featureContent = {
  access: { kicker: 'Cognitive mode / 01', title: 'Find places that feel easier to use.', lede: 'A simple signal for mental and cognitive accessibility. Look for calmer, clearer environments that match what you need today.', body: '<div class="form-stack"><label class="field-label">What kind of place are you looking for?<input id="placeSearch" type="search" placeholder="Library, cafe, clinic..." /></label><button class="primary-button" data-action="find-cognitive" type="button">Find supportive places</button><div class="results" id="placeResults"></div></div>' },
  routine: { kicker: 'Cognitive mode / 02', title: 'Keep the next thing close.', lede: 'Set a small reminder for a routine. It will stay on this device and can ask for notification permission when needed.', body: '<form class="form-stack" id="routineForm"><label class="field-label">Routine name<input name="name" required placeholder="Get ready for bed" /></label><label class="field-label">Time<input name="time" type="time" required /></label><button class="primary-button" type="submit">Add routine reminder</button></form><div class="results" id="routineResults"></div>' },
  meds: { kicker: 'Cognitive mode / 03', title: 'A gentle nudge for medication.', lede: 'Track a medication and its scheduled time. This tool supports memory; it does not replace advice from a doctor or pharmacist.', body: '<form class="form-stack" id="medForm"><label class="field-label">Medication name<input name="name" required placeholder="Medication name" /></label><label class="field-label">Dose note<input name="dose" placeholder="Optional dose or instruction" /></label><label class="field-label">Reminder time<input name="time" type="time" required /></label><button class="primary-button" type="submit">Save medication reminder</button></form><div class="results" id="medResults"></div>' },
  games: { kicker: 'Cognitive mode / 04', title: 'Practice a skill, one round at a time.', lede: 'Choose a memory game to practice. This is practice, not a medical assessment.', body: '<div class="game-selector" role="group" aria-label="Choose a cognitive game"><button class="choice-button" data-game="number" type="button">Number memory</button><button class="choice-button" data-game="items" type="button">Item recall</button></div><div class="tool-card memory-game" id="numberGame" hidden><div class="memory-game-heading"><h4>Number memory</h4><span id="gameLevel">4 numbers</span></div><p id="gamePrompt">Press start to see your first sequence.</p><div class="number-sequence" id="gameSequence" aria-live="polite"></div><label class="field-label memory-answer" for="gameAnswer">Type the numbers in order<input id="gameAnswer" type="text" inputmode="numeric" autocomplete="off" disabled /></label><div class="action-row"><button class="primary-button" data-action="start-game" type="button">Start game</button></div><p id="gameResult" aria-live="polite"></p></div><div class="tool-card item-game" id="itemGame" hidden><div class="memory-game-heading"><h4>Item recall</h4><span id="itemScore">0 / 10 correct</span></div><p id="itemPrompt">Press start to open the chest and study the items.</p><div class="item-display" id="itemDisplay"><div class="item-chest" aria-hidden="true">&#128081;</div><div class="item-countdown" id="itemCountdown">30</div><ul class="item-list" id="itemList"></ul></div><div class="item-game-over" id="itemGameOver" hidden><strong>Game Over</strong><span>That item was not in the chest.</span></div><form class="form-stack item-answer" id="itemRecallForm" hidden><label class="field-label" for="itemAnswer">Name an item you remember<input id="itemAnswer" type="text" autocomplete="off" /></label><button class="primary-button" type="submit">Submit item</button></form><div class="action-row"><button class="primary-button" data-action="start-items" type="button">Start game</button></div><p id="itemResult" aria-live="polite"></p></div>' },
  mood: { kicker: 'Cognitive mode / 05', title: 'Check in with yourself.', lede: 'Choose the feeling that is closest right now. You will get a small, optional exercise to support your next moment.', body: '<div class="choice-grid" id="moodChoices"><button class="choice-button" data-mood="overwhelmed" type="button">Overwhelmed</button><button class="choice-button" data-mood="low" type="button">Low or heavy</button><button class="choice-button" data-mood="restless" type="button">Restless</button><button class="choice-button" data-mood="okay" type="button">Okay or steady</button></div><div class="tool-card" id="moodResult" hidden><h4>Your small next step</h4><p></p></div>' },
  body: { kicker: 'Motor mode / 01', title: 'Tell us what your body needs today.', lede: 'Choose every area that feels less comfortable and every area that feels strong. Your selections shape a gentle mobility suggestion.', body: '<div class="choice-grid" id="bodyChoices"><button class="choice-button" data-body="Shoulders" type="button">Shoulders</button><button class="choice-button" data-body="Hands" type="button">Hands</button><button class="choice-button" data-body="Hips" type="button">Hips</button><button class="choice-button" data-body="Knees" type="button">Knees</button><button class="choice-button" data-body="Back" type="button">Back</button><button class="choice-button" data-body="Ankles" type="button">Ankles</button></div><button class="primary-button" data-action="mobility" type="button">Suggest mobility support</button><div class="tool-card" id="mobilityResult" hidden><h4>Gentle starting point</h4><p></p></div>' },
  physical: { kicker: 'Motor mode / 02', title: 'Know what access looks like before you go.', lede: 'Browse a sample physical-accessibility signal. In the full product, this can be connected to verified place information.', body: '<div class="results"><div class="result"><span><strong>Riverside Library</strong><small>Step-free entrance, wide aisles, accessible restroom</small></span><strong>Good access</strong></div><div class="result" style="border-color:var(--yellow)"><span><strong>Juniper Market</strong><small>Ground-level entrance, limited seating</small></span><strong>Check details</strong></div></div>' },
  large: { kicker: 'Motor mode / 03', title: 'More room. More control.', lede: 'Motor Mode is designed with bigger targets and more separation for people with tremors or reduced fine motor control.', body: '<div class="tool-card"><h4>Large touch layout</h4><p>This prototype keeps the expanded layout active while you browse. The persistent voice button is also available at the top of the page.</p><div class="meter"><span></span></div><p>Touch target size: expanded</p></div>' },
  voice: { kicker: 'Motor mode / 04', title: 'Use your voice when touch is hard.', lede: 'The voice button stays at the top of the app. Try it now, or use the button below to test browser voice recognition.', body: '<div class="tool-card"><h4>Voice control</h4><p>Say “open cognitive mode”, “open motor mode”, or “open speech mode” where browser support is available.</p><div class="action-row"><button class="primary-button" data-action="listen" type="button">Start listening</button></div></div>' },
  speechPlaces: { kicker: 'Speech mode / 01', title: 'Find places where communication can be easier.', lede: 'Look for services that offer written options, patient communication, or tools that do not require speech to be perfect.', body: '<div class="form-stack"><label class="field-label">Search by place or service<input id="speechSearch" type="search" placeholder="Pharmacy, cafe, service desk..." /></label><button class="primary-button" data-action="find-speech" type="button">Find speech-friendly places</button><div class="results" id="speechResults"></div></div>' },
  board: { kicker: 'Speech mode / 02', title: 'Let the app say it for you.', lede: 'Type a message or choose a quick response. The browser will read it aloud so you can stay part of the conversation.', body: '<div class="form-stack"><label class="field-label">Your message<textarea id="speechText" placeholder="Type what you want to say..."></textarea></label><div class="quick-responses"><button class="quick-response" data-phrase="Please give me a moment." type="button">Give me a moment</button><button class="quick-response" data-phrase="Could you write that down?" type="button">Write that down</button><button class="quick-response" data-phrase="I understand." type="button">I understand</button></div><div class="action-row"><button class="primary-button" data-action="speak-text" type="button">Speak this aloud</button><button class="secondary-button" data-action="save-phrase" type="button">Save as quick response</button></div><div class="results" id="phraseResults"></div></div>' },
  lessons: { kicker: 'Speech mode / 03', title: 'See it. Hear it. Try it.', lede: 'A gentle practice step that shows a mouth formation and plays a target word aloud.', body: '<div class="mouth-demo" aria-label="Mouth formation demonstration">ma</div><div class="tool-card"><h4 id="lessonWord">Mango</h4><p>Watch the formation, listen to the word, then practice at your own pace.</p><div class="action-row"><button class="primary-button" data-action="speak-lesson" type="button">Play word aloud</button><button class="secondary-button" data-action="next-lesson" type="button">Next word</button></div></div>' },
};

let activeMode = 'cognitive';
let activeFeature = 'access';
let gamePattern = [];
let gameLength = 4;
let itemRoundItems = [];
let itemRoundFound = [];
let itemTimer;
let itemGameOver = false;

const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));

function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('is-visible'); window.clearTimeout(showToast.timeout); showToast.timeout = window.setTimeout(() => toast.classList.remove('is-visible'), 3200); }
function speak(text) { if (!('speechSynthesis' in window)) { showToast('Speech output is not supported in this browser.'); return; } window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.rate = .9; window.speechSynthesis.speak(utterance); }
function renderFeatureList() { const list = $('#featureList'); list.innerHTML = modes[activeMode].features.map(([id, label]) => `<button class="feature-button ${id === activeFeature ? 'is-active' : ''}" data-feature="${id}" type="button">${label}</button>`).join(''); $('#modeTitle').textContent = modes[activeMode].title; }
function renderContent() { const feature = featureContent[activeFeature]; $('#featureContent').innerHTML = `<p class="feature-kicker">${feature.kicker}</p><h3>${feature.title}</h3><p class="feature-lede">${feature.lede}</p>${feature.body}`; bindFeatureEvents(); }
function selectMode(mode) { activeMode = mode; activeFeature = modes[mode].features[0][0]; document.querySelectorAll('.mode-button').forEach((button) => button.classList.toggle('is-active', button.dataset.mode === mode)); renderFeatureList(); renderContent(); }
function selectFeature(feature) { activeFeature = feature; renderFeatureList(); renderContent(); }
function renderStoredList(key, target, emptyText) { const items = JSON.parse(localStorage.getItem(key) || '[]'); const element = $(target); if (!element) return; element.innerHTML = items.length ? items.map((item) => `<div class="result"><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.detail)}</small></span><button class="secondary-button" data-remove="${key}:${item.id}" type="button">Remove</button></div>`).join('') : `<p class="feature-lede">${emptyText}</p>`; }
function saveStored(key, name, detail) { const items = JSON.parse(localStorage.getItem(key) || '[]'); items.push({ id: Date.now(), name, detail }); localStorage.setItem(key, JSON.stringify(items)); }
function bindFeatureEvents() {
  document.querySelectorAll('[data-action="find-cognitive"]').forEach((button) => button.addEventListener('click', () => { const query = $('#placeSearch').value.trim() || 'your area'; $('#placeResults').innerHTML = `<div class="result"><span><strong>Quiet ${escapeHtml(query)} options</strong><small>Lower sensory load, clear information, and a calmer pace are the details to check.</small></span><strong>Review</strong></div>`; }));
  document.querySelectorAll('[data-action="find-speech"]').forEach((button) => button.addEventListener('click', () => { const query = $('#speechSearch').value.trim() || 'nearby'; $('#speechResults').innerHTML = `<div class="result"><span><strong>Accessible ${escapeHtml(query)} options</strong><small>Look for written communication, patient service, and non-verbal ways to complete tasks.</small></span><strong>Review</strong></div>`; }));
  const routineForm = $('#routineForm'); if (routineForm) { renderStoredList('openpath-routines', '#routineResults', 'No routines yet. Add one above to keep the next step visible.'); routineForm.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(routineForm); saveStored('openpath-routines', data.get('name'), `Reminder at ${data.get('time')}`); renderStoredList('openpath-routines', '#routineResults', 'No routines yet.'); showToast('Routine reminder saved on this device.'); }); }
  const medForm = $('#medForm'); if (medForm) { renderStoredList('openpath-meds', '#medResults', 'No medication reminders yet.'); medForm.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(medForm); saveStored('openpath-meds', data.get('name'), `${data.get('dose') || 'Dose reminder'} at ${data.get('time')}`); renderStoredList('openpath-meds', '#medResults', 'No medication reminders yet.'); showToast('Medication reminder saved on this device.'); }); }
  document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => { const [key, id] = button.dataset.remove.split(':'); const items = JSON.parse(localStorage.getItem(key) || '[]').filter((item) => String(item.id) !== id); localStorage.setItem(key, JSON.stringify(items)); bindFeatureEvents(); }));
  document.querySelectorAll('[data-mood]').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('[data-mood]').forEach((item) => item.classList.remove('is-selected')); button.classList.add('is-selected'); const suggestions = { overwhelmed: 'Try naming five things you can see, then take three slow breaths.', low: 'Choose one kind, low-effort action: water, a window, or a message to someone safe.', restless: 'Try a one-minute stretch or walk, then return to the next smallest task.', okay: 'Notice what is helping right now and choose one way to protect that feeling.' }; const result = $('#moodResult'); result.hidden = false; result.querySelector('p').textContent = suggestions[button.dataset.mood]; }));
  document.querySelectorAll('[data-body]').forEach((button) => button.addEventListener('click', () => button.classList.toggle('is-selected')));
  document.querySelectorAll('[data-action="mobility"]').forEach((button) => button.addEventListener('click', () => { const chosen = [...document.querySelectorAll('[data-body].is-selected')].map((item) => item.dataset.body); const result = $('#mobilityResult'); result.hidden = false; result.querySelector('p').textContent = chosen.length ? `For ${chosen.join(', ')}, try a slow range-of-motion movement and stop if pain increases. A qualified professional can help tailor this safely.` : 'Choose one or more body areas first, then we can suggest a gentle starting point.'; }));
  document.querySelectorAll('[data-action="start-game"]').forEach((button) => button.addEventListener('click', () => { gameLength = 4; startMemoryRound(); }));
  const gameAnswer = $('#gameAnswer'); if (gameAnswer) { gameAnswer.addEventListener('input', () => { if (!gamePattern.length) return; hideMemorySequence(); const answer = gameAnswer.value.replace(/\D/g, '').slice(0, gamePattern.length); gameAnswer.value = answer; if (answer.length !== gamePattern.length) return; if (answer === gamePattern.join('')) { gameLength += 1; startMemoryRound(`Correct. Now try ${gameLength} numbers.`); } else { gameLength = 4; startMemoryRound('Almost. Starting again with 4 numbers.'); } }); }
  document.querySelectorAll('[data-game]').forEach((button) => button.addEventListener('click', () => selectGame(button.dataset.game)));
  document.querySelectorAll('[data-action="start-items"]').forEach((button) => button.addEventListener('click', startItemRecallRound));
  const itemRecallForm = $('#itemRecallForm'); if (itemRecallForm) itemRecallForm.addEventListener('submit', submitItemRecall);
  document.querySelectorAll('.quick-response').forEach((button) => button.addEventListener('click', () => { $('#speechText').value = button.dataset.phrase; }));
  document.querySelectorAll('[data-action="speak-text"]').forEach((button) => button.addEventListener('click', () => speak($('#speechText').value.trim() || 'Please give me a moment.')));
  document.querySelectorAll('[data-action="save-phrase"]').forEach((button) => button.addEventListener('click', () => { const text = $('#speechText').value.trim(); if (!text) { showToast('Type a phrase before saving it.'); return; } saveStored('openpath-phrases', text, 'Custom quick response'); showToast('Quick response saved on this device.'); renderStoredList('openpath-phrases', '#phraseResults', 'Your saved responses will appear here.'); }));
  if ($('#phraseResults')) renderStoredList('openpath-phrases', '#phraseResults', 'Your saved responses will appear here.');
  document.querySelectorAll('[data-action="speak-lesson"]').forEach((button) => button.addEventListener('click', () => speak($('#lessonWord').textContent)));
  document.querySelectorAll('[data-action="next-lesson"]').forEach((button) => button.addEventListener('click', () => { const words = ['Mango', 'Morning', 'Maybe', 'Map']; const index = words.indexOf($('#lessonWord').textContent); $('#lessonWord').textContent = words[(index + 1) % words.length]; showToast('Next practice word loaded.'); }));
  document.querySelectorAll('[data-action="listen"]').forEach((button) => button.addEventListener('click', startVoiceControl));
}
function selectGame(game) { clearInterval(itemTimer); document.querySelectorAll('[data-game]').forEach((button) => button.classList.toggle('is-selected', button.dataset.game === game)); const numberGame = $('#numberGame'); const itemGame = $('#itemGame'); if (!numberGame || !itemGame) return; numberGame.hidden = game !== 'number'; itemGame.hidden = game !== 'items'; }
function startMemoryRound(message = '') { gamePattern = Array.from({ length: gameLength }, () => Math.floor(Math.random() * 10)); const sequence = $('#gameSequence'); const answer = $('#gameAnswer'); if (!sequence || !answer) return; sequence.innerHTML = gamePattern.map((number) => `<span class="number-bubble">${number}</span>`).join(''); sequence.classList.remove('is-hidden'); $('#gameLevel').textContent = `${gameLength} numbers`; $('#gamePrompt').textContent = 'Look at the numbers, then type them in the same order.'; $('#gameResult').textContent = message; answer.value = ''; answer.disabled = false; answer.focus(); }
function hideMemorySequence() { const sequence = $('#gameSequence'); if (!sequence || sequence.classList.contains('is-hidden')) return; sequence.classList.add('is-hidden'); sequence.textContent = 'The numbers are hidden. Keep going.'; $('#gamePrompt').textContent = 'The numbers are hidden. Type the sequence from memory.'; }
function startItemRecallRound() { const itemBank = ['apple', 'book', 'key', 'umbrella', 'cup', 'star', 'pencil', 'shoe', 'camera', 'flower', 'ball', 'hat', 'clock', 'guitar', 'bicycle', 'candle', 'shell', 'scarf', 'coin', 'backpack', 'banana', 'bottle', 'bridge', 'cloud', 'drum', 'feather', 'glasses', 'leaf', 'moon', 'orange', 'pillow', 'rainbow', 'ring', 'rocket', 'spoon', 'teddy bear', 'toothbrush', 'train', 'tree', 'watch']; itemRoundItems = itemBank.map((item) => ({ item, sort: Math.random() })).sort((a, b) => a.sort - b.sort).slice(0, 10).map(({ item }) => item); itemRoundFound = []; itemGameOver = false; clearInterval(itemTimer); const itemList = $('#itemList'); const itemForm = $('#itemRecallForm'); const gameOver = $('#itemGameOver'); const itemDisplay = $('#itemDisplay'); if (!itemList || !itemForm || !gameOver || !itemDisplay) return; itemList.innerHTML = itemRoundItems.map((item) => `<li>${item}</li>`).join(''); itemDisplay.classList.remove('is-hidden'); gameOver.hidden = true; $('#itemCountdown').textContent = '30'; $('#itemPrompt').textContent = 'Study the items before the chest closes.'; $('#itemResult').textContent = ''; $('#itemScore').textContent = '0 / 10 correct'; itemForm.hidden = true; itemForm.reset(); let seconds = 30; itemTimer = window.setInterval(() => { const countdown = $('#itemCountdown'); if (!countdown) { clearInterval(itemTimer); return; } seconds -= 1; countdown.textContent = seconds; if (seconds <= 0) { clearInterval(itemTimer); itemDisplay.classList.add('is-hidden'); itemForm.hidden = false; $('#itemPrompt').textContent = 'The chest is closed. How many items can you remember?'; $('#itemAnswer').focus(); } }, 1000); }
function submitItemRecall(event) { event.preventDefault(); if (itemGameOver) return; const answer = $('#itemAnswer').value.trim().toLowerCase(); if (!answer) return; const result = $('#itemResult'); if (itemRoundItems.includes(answer) && !itemRoundFound.includes(answer)) { itemRoundFound.push(answer); $('#itemScore').textContent = `${itemRoundFound.length} / 10 correct`; result.textContent = itemRoundFound.length === 10 ? 'You remembered all 10 items.' : 'Correct. Name another item.'; } else if (itemRoundFound.includes(answer)) { result.textContent = 'You already named that item. Try another one.'; } else { itemGameOver = true; $('#itemRecallForm').hidden = true; $('#itemGameOver').hidden = false; $('#itemPrompt').textContent = 'Your round has ended.'; result.textContent = 'Game over. Press Start game to try again.'; } $('#itemAnswer').value = ''; }
function startVoiceControl() { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) { showToast('Voice control needs a browser with speech recognition support.'); return; } const recognition = new Recognition(); recognition.lang = 'en-US'; recognition.onstart = () => { $('#voiceButton').classList.add('voice-listening'); showToast('Listening for a mode command...'); }; recognition.onend = () => $('#voiceButton').classList.remove('voice-listening'); recognition.onerror = () => showToast('I could not hear that. Try again.'); recognition.onresult = (event) => { const text = event.results[0][0].transcript.toLowerCase(); const mode = Object.keys(modes).find((key) => text.includes(key)); if (mode) { selectMode(mode); showToast(`Opening ${mode} mode.`); } else { showToast('Try saying cognitive, motor, or speech mode.'); } }; recognition.start(); }

document.querySelectorAll('.mode-button').forEach((button) => button.addEventListener('click', () => selectMode(button.dataset.mode)));
document.addEventListener('click', (event) => { const feature = event.target.closest('[data-feature]'); if (feature) selectFeature(feature.dataset.feature); });
$('#voiceButton').addEventListener('click', startVoiceControl);
$('#dateLabel').textContent = new Intl.DateTimeFormat('en', { weekday: 'long', month: 'short', day: 'numeric' }).format(new Date());
renderFeatureList();
renderContent();
